apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-blue.yaml
- deployment-green.yaml
- service-blue.yaml
- service-green.yaml
- ingress.yaml
images:
- name: hello-gitops
  newName: pabyrivskyiv/hello-gitops
  newTag: 174681a3b1e9b176ea5ac5aa508957d5b43e7239
