apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-green.yaml
- deployment-blue.yaml
- ingress.yaml
images:
- name: hello-gitops
  newName: pabyrivskyiv/hello-gitops
  newTag: 102f35e58e463f6975749568bf4c38b7561f2f57
