apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: pabyrivskyiv/hello-gitops
  newTag: fef25fa1e9ee817dd377916a3a20e5a40cd54a44
