apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-blue.yaml
- deployment-green.yaml
- service.yaml
- ingress.yaml
images:
- name: hello-gitops
  newName: pabyrivskyiv/hello-gitops
  newTag: cf1cc2334178bd0b0b48cbfa70ec09cbac801995
